import Header from '@/components/shared/Header'
import type { Metadata } from 'next'
import 'slick-carousel/slick/slick-theme.css'
import 'slick-carousel/slick/slick.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='container mx-auto min-h-[100vh] bg-gradient-bg'>
        <header>
          <Header />
        </header>
        {children}
      </body>
    </html>
  )
}
